language: r

warnings_are_errors: false
cache: packages
sudo: required
branches:
    only:
    - master

r_packages:
    - devtools
    - dplyr
    - rmarkdown
    - knitr
    - renv


r_github_packages:
    - ewenharrison/finalfit

before_script:
    - Rscript -e 'print("before script")'

script:
    - Rscript -e 'rmarkdown::render_site()'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: master
    local_dir: docs
    target_branch: gh-pages
addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev
