project:
  type: book
  output-dir: public

book:
  title: "Histopathology Template"
  author:
   - name: "Serdar Balc覺"
     url: "https://www.serdarbalci.com"
     affiliation: "Memorial Patoloji"
     affiliation-url: "https://patoloji.memorial.com.tr/"
     orcid: "0000-0002-7852-3851"
  date: last-modified

  chapters:
    - index.qmd
    - references.qmd

  page-footer:
    border: true
    background: light
    left: "[patolojiAI](https://www.patolojiai.com/) - [Serdar Balc覺](https://www.serdarbalci.com/)"
    right: "[Patoloji Atlas覺](https://www.patolojiatlasi.com/) - [Patoloji Notlar覺](https://www.patolojinotlari.com/) - [ParaPathology](https://www.parapathology.com/)"


bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true


editor: source

freeze: false
