---
title: "Histopathology Research Template"
description: |
  Codes Used in Histopathology Research  
  Data Report for Histopathology Research  
  Example Using Random Generated Fakedata
author:
  - name: Serdar Balci, MD, Pathologist
    url: https://sbalci.github.io/histopathology-template/
    affiliation: serdarbalci.com
    affiliation_url: https://www.serdarbalci.com/
date: "`r Sys.Date()`"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{xcolor}
- \usepackage{afterpage}
output: 
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
  pdf_document: 
    fig_caption: yes
    highlight: kate
    number_sections: yes
    toc: yes
    latex_engine: lualatex
    toc_depth: 5
    keep_tex: yes
  redoc::redoc:
    highlight_outputs: TRUE
    margins: 1 
    line_numbers: FALSE 
  distill::distill_article:
    toc: true
vignette: >
  %\VignetteIndexEntry{Recommendations for Rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---


## Header Codes


```{r header, child = here::here('childRmd', '_header.Rmd')}
```


---


## Import Data


```{r importData, child = here::here('childRmd', '_importData.Rmd')}
```


---


<!-- ```{r overview, child = here::here('childRmd', '_overView.Rmd')} -->
<!-- ``` -->


<!-- ```{r data dictionary, child = here::here('childRmd', '_dataDictionary.Rmd')} -->
<!-- ``` -->




<!-- ```{r clean and recode, child = here::here('childRmd', '_cleanRecode.Rmd')} -->
<!-- ``` -->




<!-- ```{r impute, child = here::here('childRmd', '_impute.Rmd')} -->
<!-- ``` -->



<!-- \pagebreak -->



<!-- ```{r descriptives, child = here::here('childRmd', '_descriptives.Rmd')} -->
<!-- ``` -->


<!-- \newpage -->
<!-- \blandscape -->

<!-- ```{r crossTables, child = here::here('childRmd', '_crossTables.Rmd')} -->
<!-- ``` -->

<!-- \elandscape -->


<!-- ```{r plots, child = here::here('childRmd', '_plots.Rmd')} -->
<!-- ``` -->




<!-- ```{r pairedTests, child = here::here('childRmd', '_pairedTests.Rmd')} -->
<!-- ``` -->



<!-- ```{r hypothesisTests, child = here::here('childRmd', '_hypothesisTests.Rmd')} -->
<!-- ``` -->

<!-- \newpage -->
<!-- \blandscape -->



<!-- ```{r ROC, child = here::here('childRmd', '_ROC.Rmd')} -->
<!-- ``` -->


<!-- ```{r Decision Tree, child = here::here('childRmd', '_decisionTree.Rmd')} -->
<!-- ``` -->




<!-- ```{r survival, child = here::here('childRmd', '_survival.Rmd')} -->
<!-- ``` -->

<!-- \elandscape -->


<!-- ```{r models, child = here::here('childRmd', '_models.Rmd')} -->
<!-- ``` -->


<!-- \pagebreak -->



<!-- ```{r comments, child = here::here('childRmd', '_comments.Rmd')} -->
<!-- ``` -->



<!-- \pagebreak -->


<!-- ```{r footer, child = here::here('childRmd', '_footer.Rmd')} -->
<!-- ``` -->


<!-- \pagebreak -->



<!-- \newpage -->


<!-- ```{r git update, include=FALSE} -->
<!-- source(file = here::here("R", "gitUpdateCommitPush.R")) -->
<!-- ``` -->




