---
title: "Histopathology Research Template"
description: |
  Codes Used in Histopathology Research  
  Data Report for Histopathology Research
author:
  - name: Serdar Balci, MD, Pathologist
    url: https://sbalci.github.io/histopathology-template/
    affiliation: serdarbalci.com
    affiliation_url: https://www.serdarbalci.com/
date: "<span class="redoc" id="redoc-inlinecode-1">`r Sys.Date()`</span>"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{xcolor}
- \definecolor{fancyTextColor}{HTML}{4284f5}
- \definecolor{fancyTextColor}{RGB}{66, 132, 245}
- \definecolor{fancyTextColor}{rgb}{0.258, 0.517, 0.960}
- \usepackage{afterpage}
output: 
  redoc::redoc:
    highlight_outputs: TRUE
    margins: 1 
    line_numbers: FALSE 
  rmarkdown::html_vignette: 
    css: 
    - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
  distill::distill_article:
    toc: true
  pdf_document: 
    fig_caption: yes
    highlight: kate
    number_sections: yes
    toc: yes
    latex_engine: lualatex
    toc_depth: 5
    keep_tex: yes
vignette: >
  %\VignetteIndexEntry{Recommendations for Rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---


<div class="redoc" id="redoc-codechunk-1">
```{r header, child = here::here('childRmd', '_header.Rmd')}
```

</div>


<div class="redoc" id="redoc-codechunk-2">
```{r importData, child = here::here('childRmd', '_importData.Rmd')}
```

</div>


<span class="redoc" id="redoc-htmlcomment-1"><!-- <div class="redoc" id="redoc-codechunk-3">
```{r overview, child = here::here('childRmd', '_overView.Rmd')} -->
<!-- ``` 

</div>--></span>


<div class="redoc" id="redoc-codechunk-4">
```{r explore data dictionary, eval=FALSE, include=FALSE}
# iris %>% explore::data_dict_md(output_dir = here::here())
# description <- data.frame(
#                   variable = c("Species"), 
#                   description = c("Species of Iris flower"))

data_dict_md(data = mydata, 
             title = "Data Set", 
             # description =  description, 
             output_file = "data_dict.md",
             output_dir = here::here("childRmd"))
```

</div>


<span class="redoc" id="redoc-htmlcomment-2"><!-- <div class="redoc" id="redoc-codechunk-5">
```{r data dictionary, child = here::here('childRmd', 'data_dict.md')} -->
<!-- ``` 

</div>--></span>




<div class="redoc" id="redoc-codechunk-6">
```{r clean and recode, child = here::here('childRmd', '_cleanRecode.Rmd')}
```

</div>




<div class="redoc" id="redoc-codechunk-7">
```{r impute, child = here::here('childRmd', '_impute.Rmd')}
```

</div>




<div class="redoc" id="redoc-latex-1">
<div class="redoc" id="redoc-latex-8">
\pagebreak

</div>

</div>



<div class="redoc" id="redoc-codechunk-8">
```{r descriptives, child = here::here('childRmd', '_descriptives.Rmd')}
```

</div>


<div class="redoc" id="redoc-latex-2">
<div class="redoc" id="redoc-latex-5">
<div class="redoc" id="redoc-latex-9">
\newpage

</div>

</div>

</div>
<div class="redoc" id="redoc-latex-3">
<div class="redoc" id="redoc-latex-6">
\blandscape

</div>

</div>

<div class="redoc" id="redoc-codechunk-9">
```{r crossTables, child = here::here('childRmd', '_crossTables.Rmd')}
```

</div>

<div class="redoc" id="redoc-latex-4">
<div class="redoc" id="redoc-latex-7">
\elandscape

</div>

</div>


<div class="redoc" id="redoc-codechunk-10">
```{r plots, child = here::here('childRmd', '_plots.Rmd')}
```

</div>




<span class="redoc" id="redoc-htmlcomment-3"><!-- <div class="redoc" id="redoc-codechunk-11">
```{r pairedTests, child = here::here('childRmd', '_pairedTests.Rmd')} -->
<!-- ``` 

</div>--></span>



<span class="redoc" id="redoc-htmlcomment-4"><!-- <div class="redoc" id="redoc-codechunk-12">
```{r hypothesisTests, child = here::here('childRmd', '_hypothesisTests.Rmd')} -->
<!-- ``` 

</div>--></span>

\newpage
\blandscape



<div class="redoc" id="redoc-codechunk-13">
```{r ROC, child = here::here('childRmd', '_ROC.Rmd')}
```

</div>


<div class="redoc" id="redoc-codechunk-14">
```{r Decision Tree, child = here::here('childRmd', '_decisionTree.Rmd')}
```

</div>




<div class="redoc" id="redoc-codechunk-15">
```{r survival, child = here::here('childRmd', '_survival.Rmd')}
```

</div>

\elandscape


<div class="redoc" id="redoc-codechunk-16">
```{r models, child = here::here('childRmd', '_models.Rmd')}
```

</div>





<div class="redoc" id="redoc-codechunk-17">
```{r footer, child = here::here('childRmd', '_footer.Rmd')}
```

</div>


\pagebreak



\newpage


<div class="redoc" id="redoc-codechunk-18">
```{r git update}
source(file = here::here("R", "gitUpdateCommitPush.R"))
```

</div>




