```{r DiffuzBuyume}
frequencyColumns %>% 
  janitor::tabyl(DiffuzBuyume) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r KonfluenNekroz}
frequencyColumns %>% 
  janitor::tabyl(KonfluenNekroz) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r ArtmisHucresellik}
frequencyColumns %>% 
  janitor::tabyl(ArtmisHucresellik) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Monotonluk}
frequencyColumns %>% 
  janitor::tabyl(Monotonluk) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r igsilesme}
frequencyColumns %>% 
  janitor::tabyl(igsilesme) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Mitoz}
frequencyColumns %>% 
  janitor::tabyl(Mitoz) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r AtipikMitoz}
frequencyColumns %>% 
  janitor::tabyl(AtipikMitoz) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r AdipozDokuUzanim}
frequencyColumns %>% 
  janitor::tabyl(AdipozDokuUzanim) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Vaskulerinvazyon}
frequencyColumns %>% 
  janitor::tabyl(Vaskulerinvazyon) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Kapsulinvazyon}
frequencyColumns %>% 
  janitor::tabyl(Kapsulinvazyon) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r pleomorfizm}
frequencyColumns %>% 
  janitor::tabyl(pleomorfizm) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r hiperkromazi}
frequencyColumns %>% 
  janitor::tabyl(hiperkromazi) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r skorPASS}
frequencyColumns %>% 
  janitor::tabyl(skorPASS) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r BuyukDuzensizYuvalanma}
frequencyColumns %>% 
  janitor::tabyl(BuyukDuzensizYuvalanma) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r psodorozet}
frequencyColumns %>% 
  janitor::tabyl(psodorozet) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r HucreSayisi}
frequencyColumns %>% 
  janitor::tabyl(HucreSayisi) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r komedonekroz}
frequencyColumns %>% 
  janitor::tabyl(komedonekroz) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r DamarKapsulinvazyonu}
frequencyColumns %>% 
  janitor::tabyl(DamarKapsulinvazyonu) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r ki67_gr}
frequencyColumns %>% 
  janitor::tabyl(ki67_gr) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r skorGAPP}
frequencyColumns %>% 
  janitor::tabyl(skorGAPP) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r modifiyeGAPP}
frequencyColumns %>% 
  janitor::tabyl(modifiyeGAPP) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r CevreSurrenal}
frequencyColumns %>% 
  janitor::tabyl(CevreSurrenal) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r NukleerPsodoinkluzyon}
frequencyColumns %>% 
  janitor::tabyl(NukleerPsodoinkluzyon) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r HyalenGlobul}
frequencyColumns %>% 
  janitor::tabyl(HyalenGlobul) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r BerrakHucre}
frequencyColumns %>% 
  janitor::tabyl(BerrakHucre) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r LipofuskinMelanin}
frequencyColumns %>% 
  janitor::tabyl(LipofuskinMelanin) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r GanglionHucresi}
frequencyColumns %>% 
  janitor::tabyl(GanglionHucresi) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r SmallCell}
frequencyColumns %>% 
  janitor::tabyl(SmallCell) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r VaskulerPaternAnomalisi}
frequencyColumns %>% 
  janitor::tabyl(VaskulerPaternAnomalisi) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r SustantakulerHucre}
frequencyColumns %>% 
  janitor::tabyl(SustantakulerHucre) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r CerrahiSinir}
frequencyColumns %>% 
  janitor::tabyl(CerrahiSinir) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Tani}
frequencyColumns %>% 
  janitor::tabyl(Tani) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Lokalizasyon}
frequencyColumns %>% 
  janitor::tabyl(Lokalizasyon) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


```{r Cinsiyet}
frequencyColumns %>% 
  janitor::tabyl(Cinsiyet) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```


