---
title: "Karaciğer rejeksiyonlarında donör yaşının etkisi"
description: |
  A new article created using the Distill format.
author:
  - name: Asude Ayhan 
    url: 
    affiliation: Başkent
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    fig_caption: yes
    highlight: kate
    number_sections: yes
    toc: yes
    latex_engine: lualatex
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)
```



```{r load library}
source("R/loadLibrary.R")
```


```{r import data clean names, message=FALSE, warning=FALSE}
karaciger_trans_donor <- read_excel("data/karaciger-trans-donor.xlsx", 
    col_types = c("numeric", "numeric", "text", 
        "text", "text", "date", "numeric", 
        "numeric", "numeric", "text", "date", 
        "text", "text", "text", "date", "text", 
        "text", "text", "text", "date", "date", 
        "date", "date", "numeric", "numeric")) %>%
  janitor::clean_names()
```



```{r recode}
karaciger_trans_donor <- karaciger_trans_donor %>% 
  mutate(
    verici = case_when(
      verici_ad_soyadi == "kadavra" ~ "kadavra",
      TRUE ~ "canli"
    )
  )
```


```{r recode date}
# Yaşayan tüm hastalar için son görülme tarihini güncelle
karaciger_trans_donor$overall_survival_son_tarih[karaciger_trans_donor$olum == "yok"] <- as.Date("2019-05-01 UTC")
```



```{r define overall survival time}
karaciger_trans_donor$int <- interval(
  lubridate::ymd(karaciger_trans_donor$tx_tarihi),
  lubridate::ymd(karaciger_trans_donor$overall_survival_son_tarih)
  )
karaciger_trans_donor$OverallTime <- lubridate::time_length(karaciger_trans_donor$int, "month")
karaciger_trans_donor$OverallTime <- round(karaciger_trans_donor$OverallTime, digits = 1)
```


```{r define overall outcome}
## Recoding karaciger_trans_donor$olum into karaciger_trans_donor$OverallOutcome
karaciger_trans_donor$OverallOutcome <- recode(karaciger_trans_donor$olum,
               "var" = "1",
               "yok" = "0")
karaciger_trans_donor$OverallOutcome <- as.numeric(karaciger_trans_donor$OverallOutcome)
```



```{r define rejection free survival time}
karaciger_trans_donor$rejint <- interval(
  ymd(karaciger_trans_donor$tx_tarihi),
  ymd(karaciger_trans_donor$rejection_free_son_tarih)
  )
karaciger_trans_donor$RejectionFreeTime <- time_length(karaciger_trans_donor$rejint, "month")
karaciger_trans_donor$RejectionFreeTime <- round(karaciger_trans_donor$RejectionFreeTime, digits = 1)
```



```{r define rejection free outcome}
## Recoding karaciger_trans_donor$olum into karaciger_trans_donor$OverallOutcome
karaciger_trans_donor$RejectionFreeOutcome <- recode(karaciger_trans_donor$rejeksiyon_18,
               "var" = "1",
               "yok" = "0")
karaciger_trans_donor$RejectionFreeOutcome <- as.numeric(karaciger_trans_donor$RejectionFreeOutcome)
```



```{r verici yas grubu}
karaciger_trans_donor <- karaciger_trans_donor %>% 
  mutate(
    vericiYasGr = case_when(
      tx_zamani_verici_yasi >= 50 & tx_zamani_verici_yasi <55 ~ "50-54",
      tx_zamani_verici_yasi >= 55 & tx_zamani_verici_yasi <60 ~ "55-59",
      tx_zamani_verici_yasi >= 60 & tx_zamani_verici_yasi <70 ~ "60-69",
      tx_zamani_verici_yasi >= 70 ~ "70uzeri"
    )
  )
```





# Descriptive Statistics


```{r yas}
jmv::descriptives(
    data = karaciger_trans_donor,
    vars = tx_zamani_verici_yasi,
    hist = TRUE,
    dens = TRUE,
    box = TRUE,
    violin = TRUE,
    dot = TRUE,
    sd = TRUE,
    quart = TRUE)
```




```{r yas grup}
karaciger_trans_donor %>% 
  janitor::tabyl(vericiYasGr) %>%
  adorn_pct_formatting(rounding = 'half up', digits = 1) %>%
  knitr::kable()
```



# Survival


## Overall Survival


### Overall Survival Verici Yaşına Göre

```{r include=FALSE}
library(survival)
km <- with(karaciger_trans_donor, Surv(OverallTime, OverallOutcome))
head(km,80)
plot(km)
```





```{r Kaplan-Meier Overall YasGr}
explanatoryKM_Overall_YasGr <-  c("vericiYasGr")
dependentKM_Overall_YasGr <-  "Surv(OverallTime, OverallOutcome)"
karaciger_trans_donor %>%
  finalfit::surv_plot(dependentKM_Overall_YasGr, explanatoryKM_Overall_YasGr, 
  xlab="Time (months)", pval=TRUE, legend = "none")
```



```{r}
km_fit_Overall_YasGr <- survfit(Surv(OverallTime, OverallOutcome) ~ vericiYasGr, data = karaciger_trans_donor)
km_fit_Overall_YasGr
```


```{r 1-3-5-yr survival Overall YasGr}
summary(km_fit_Overall_YasGr, times = c(12,36,60))
```





### Overall Survival Kadavra vs Canlı Verici

```{r eval=FALSE, include=FALSE}
library(survival)
km <- with(karaciger_trans_donor, Surv(OverallTime, OverallOutcome))
head(km,80)
plot(km)
```





```{r Kaplan-Meier Overall verici turu}
explanatoryKM_Overall <-  c("verici")
dependentKM_Overall <-  "Surv(OverallTime, OverallOutcome)"
karaciger_trans_donor %>%
  finalfit::surv_plot(dependentKM_Overall, explanatoryKM_Overall, 
  xlab="Time (months)", pval=TRUE, legend = "none")
```



```{r}
km_fit_Overall <- survfit(Surv(OverallTime, OverallOutcome) ~ verici, data = karaciger_trans_donor)
km_fit_Overall
```


```{r 1-3-5-yr Overall survival verici turu}
summary(km_fit_Overall, times = c(12,36,60))
```




## Rejeksiyon Free Survival


### Rejeksiyon Free Survival Verici Yaşına Göre

```{r include=FALSE}
library(survival)
km <- with(karaciger_trans_donor, Surv(RejectionFreeTime, RejectionFreeOutcome))
head(km,80)
plot(km)
```





```{r Kaplan-Meier Rej Free YasGr}
explanatoryKM_RejFree_YasGr <-  c("vericiYasGr")
dependentKM_RejFree_YasGr <-  "Surv(RejectionFreeTime, RejectionFreeOutcome)"

karaciger_trans_donor %>%
  finalfit::surv_plot(dependentKM_RejFree_YasGr, explanatoryKM_RejFree_YasGr, 
  xlab="Time (months)", pval=TRUE, legend = "none")
```



```{r}
km_fit_RejFree_YasGr <- survfit(Surv(RejectionFreeTime, RejectionFreeOutcome) ~ vericiYasGr, data = karaciger_trans_donor)
km_fit_RejFree_YasGr
```


```{r 1-3-5-yr survival RejFree YasGr}
summary(km_fit_RejFree_YasGr, times = c(12,36,60))
```





### Rejeksiyon Free Survival Kadavra vs Canlı Verici

```{r eval=FALSE, include=FALSE}
library(survival)
km <- with(karaciger_trans_donor, Surv(RejectionFreeTime, RejectionFreeOutcome))
head(km,80)
plot(km)
```





```{r Kaplan-Meier Rej Free verici turu}
explanatoryKM_RejFree_verici <-  c("verici")
dependentKM_RejFree_verici <-  "Surv(RejectionFreeTime, RejectionFreeOutcome)"

karaciger_trans_donor %>%
  finalfit::surv_plot(dependentKM_RejFree_verici, explanatoryKM_RejFree_verici, 
  xlab="Time (months)", pval=TRUE, legend = "none")
```



```{r}
km_fit_RejFree_verici <- survfit(Surv(RejectionFreeTime, RejectionFreeOutcome) ~ verici, data = karaciger_trans_donor)
km_fit_Overall
```


```{r 1-3-5-yr Rej Free survival verici turu}
summary(km_fit_RejFree_verici, times = c(12,36,60))
```










```{r child='_footer.Rmd'}
```





