

```{r load library, eval=FALSE, include=FALSE}
#  https://easystats.github.io/correlation/
# install.packages("devtools")
# devtools::install_github("easystats/correlation")
library("correlation")
```


```{r correlation, eval=FALSE, include=FALSE}
correlation(iris)
```



```{r correlation 2, eval=FALSE, include=FALSE}
library(dplyr)

iris %>% 
  select(Species, starts_with("Sepal")) %>% 
  group_by(Species) %>% 
  correlation() %>% 
  filter(r < 0.9)

```

  
  
```{r correlation 3, eval=FALSE, include=FALSE}
correlation(select(iris, Species, starts_with("Sepal")),
            select(iris, Species, starts_with("Petal")),
            partial=TRUE)

```
  
            
            
```{r correlation bayesian, eval=FALSE, include=FALSE}
correlation(iris, bayesian=TRUE)

```



```{r correlation report, eval=FALSE, include=FALSE}
library(report)
iris %>% 
  select(starts_with("Sepal")) %>% 
  correlation(bayesian=TRUE) %>% 
  report()

```

  
```{r correlation report 2, eval=FALSE, include=FALSE}
iris %>% 
  group_by(Species) %>% 
  correlation() %>% 
  report() %>% 
  to_table()

```

  
























