# Descriptive Statistics


## Table 1  

```{r report data}
report::report(mydata)
```



```{r arsenal Table 1, results='asis'}
# cat(names(mydata), sep = " + \n")

library(arsenal)
tab1 <- tableby(~ Cinsiyet + 
Yas
                ,
                data = mydata)
summary(tab1)
```


<!-- https://cran.r-project.org/web/packages/tableone/index.html -->
<!-- https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html -->



```{r tableone}
library(tableone)
library(survival)
data(pbc)
CreateTableOne(data = pbc)
```


```{r tableone 2}
CreateTableOne(vars = myVars, data = pbc, factorVars = catVars)
```


```{r tableone 3}
tab <- CreateTableOne(vars = myVars, data = pbc, factorVars = catVars)
print(tab, showAllLevels = TRUE)
?print.TableOne
summary(tab)
```




```{r tableone nonnormal values}
print(tab, nonnormal = biomarkers)
```


```{r tableone copy to excel}
print(tab, nonnormal = biomarkers, exact = "stage", quote = TRUE, noSpaces = TRUE)
```


```{r tableone export to csv}
tab3Mat <- print(tab3, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
# write.csv(tab3Mat, file = "myTable.csv")
```



<!-- atable -->
<!-- https://cran.r-project.org/web/packages/atable/vignettes/atable_usage.pdf -->
<!-- https://journal.r-project.org/archive/2019/RJ-2019-001/index.html -->




```{r summarytools descriptives 1}
descr(tobacco, style = 'rmarkdown')
```


```{r summarytools descriptives 2}
print(descr(tobacco), method = 'render', table.classes = 'st-small')
```
 


```{r summarytools descriptives 3}
summarytools::descr(iris, style = "rmarkdown")
descr(iris, stats = "common", transpose = TRUE, headings = FALSE)
```



```{r summarytools descriptives 4}
iris %>% descr(stats = "common") %>% tb()
iris$Species %>% freq(cumul = FALSE, report.nas = FALSE) %>% tb()
```




```{r explore descriptive statistics}
iris %>% explore::describe()
iris %>% explore::describe() %>% dplyr::filter(unique < 5)
iris %>% explore::describe() %>% dplyr::filter(na > 0)
```



---




## Categorical Variables



```{r print names as vector}
dput(names(pbc))
```



```{r select categorical variables}
mydataCategorical <- mydata %>% 
    select(-Yas,
           -TumorCapi,
           -CerrahiTarih,
           -genel_sagkalim,
           -SonTarih,
           -TNM
    )
```



```{r define continious variables 1}
mydataDescription <- describer::describe(iris)

mydataDescription %>% 
    janitor::clean_names() %>% 
    dplyr::filter(column_class == "factor") %>% 
    dplyr::select(column_name) %>% 
    dplyr::pull() -> categoricalVariables
```




```{r generate Code descriptive}
source(here::here("R", "generatingCodeForDescriptiveStatistics.R"))
```


```{r generatedCodeDescriptives, child = here::here('childRmd', 'generatedCodeDescriptives.Rmd')}
```


```{r tableone categorical}
tab <- tableone::CreateTableOne(data = pbc)
?print.CatTable
tab$CatTable
```



```{r summarytools Categorical}
(age_stats <- freq(tobacco$age.gr)) 
print(age_stats, report.nas = FALSE, totals = FALSE, display.type = FALSE,
      Variable.label = "Age Group")
```




```{r explore categorical variables}
iris %>% explore::describe(Species)
```


```{r SmartEDA 1}
## Frequency or custom tables for categorical variables
SmartEDA::ExpCTable(
  Carseats,
  Target = NULL,
  margin = 1,
  clim = 10,
  nlim = 5,
  round = 2,
  bin = NULL,
  per = T
)
```



```{r inspectdf 2}
# some example data
data(starwars, package = "dplyr")
data(storms, package = "dplyr")
star_1 <- starwars %>% sample_n(50)
star_2 <- starwars %>% sample_n(50) %>% select(-1, -2)

inspectdf::inspect_cat(starwars)

inspectdf::inspect_cat(starwars)$levels$hair_color
```



### Split-Group Stats Categorical

```{r summarytools Split-Group categorical}
grouped_freqs <- stby(data = tobacco$smoker, 
                      INDICES = tobacco$gender, 
                      FUN = freq, cumul = FALSE, report.nas = FALSE)
grouped_freqs %>% tb()

grouped_freqs %>% tb(order = 2)
```






### Grouped Categorical

```{r summarytools Grouped Categorical}
stby(list(x = tobacco$smoker, y = tobacco$diseased), tobacco$gender, ctable)
with(tobacco, stby(list(x = smoker, y = diseased), gender, ctable))
```




```{r SmartEDA category 1}
SmartEDA::ExpCTable(
  Carseats,
  Target = "Price",
  margin = 1,
  clim = 10,
  nlim = NULL,
  round = 2,
  bin = 4,
  per = F
)
```





\pagebreak


---


## Continious Variables


```{r categorise cut off continious variables}
questionr:::icut()
```



```{r select continious variables}
mydataContinious <- mydata %>% 
    select(
        Yas,
        TumorCapi
    )
```



```{r define continious variables}
mydataDescription <- describer::describe(iris)

mydataDescription %>% 
    janitor::clean_names() %>% 
    dplyr::filter(column_class == "numeric") %>% 
    dplyr::select(column_name) %>% 
    dplyr::pull() -> continiousVariables
```



```{r generate Code Continious}
source(here::here("R", "generatingCodeForContinious.R"))
```



```{r generatedCodeContinious, child = here::here('childRmd', 'generatedCodeContinious.Rmd')}
```



```{r tableone continious}
tab <- tableone::CreateTableOne(data = pbc)
?print.ContTable
tab$ContTable
print(tab$ContTable, nonnormal = c("albumin", "copper"))
```



```{r explore continious variables}
iris %>% explore::describe(Sepal.Length)
```


```{r SmartEDA}
## Summary statistics by – overall
SmartEDA::ExpNumStat(
  Carseats,
  by = "A",
  gp = NULL,
  Qnt = seq(0, 1, 0.1),
  MesofShape = 2,
  Outlier = TRUE,
  round = 2
)
```





```{r inspectdf 3}
inspectdf::inspect_num(storms, breaks = 10)

inspectdf::inspect_num(storms)$hist$pressure

inspectdf::inspect_num(storms, breaks = 10) %>%
  inspectdf::show_plot()

inspectdf::inspect_num(storms, storms[-c(1:10), -1])

inspectdf::inspect_num(storms, storms[-c(1:10), -1]) %>% 
  inspectdf::show_plot()
```














### Split-Group Stats Continious


```{r summarytools Split-Group continious}
grouped_descr <- stby(data = exams, 
                      INDICES = exams$gender, 
                      FUN = descr, stats = "common")
grouped_descr %>% tb()

grouped_descr %>% tb(order = 2)
```


```{r dlookr}
carseats %>%
  group_by(US) %>% 
  dlookr::describe(Sales, Income) 

carseats %>%
  group_by(US, Urban) %>% 
  dlookr::describe(Sales, Income) 

```




```{r dlookr target}
categ <- dlookr::target_by(carseats, US)
cat_num <- dlookr::relate(categ, Sales)
cat_num
summary(cat_num)
plot(cat_num)
```






### Grouped Continious

```{r summarytools Grouped Continious}
(iris_stats_by_species <- stby(data = iris, 
                               INDICES = iris$Species, 
                               FUN = descr, stats = c("mean", "sd", "min", "med", "max"), 
                               transpose = TRUE))
```



```{r summarytools Grouped Continious 2}
with(tobacco, stby(BMI, age.gr, descr, 
                   stats = c("mean", "sd", "min", "med", "max"),
                   transpose = TRUE
                   )
     )
```



```{r summarytools Grouped Continious 3}
tobacco$gender <- forcats::fct_explicit_na(tobacco$gender)
tobacco %>% group_by(gender) %>% descr(stats = "fivenum")
```



```{r SmartEDA category}
## Summary statistics by – category
SmartEDA::ExpNumStat(
  Carseats,
  by = "GA",
  gp = "Urban",
  Qnt = seq(0, 1, 0.1),
  MesofShape = 2,
  Outlier = TRUE,
  round = 2
)
```



\pagebreak










