**Cross Table PreinvasiveComponent** 

```{r crosstable finalfit PreinvasiveComponent, message=FALSE, warning=FALSE}
mydata %>%
    summary_factorlist(dependent = 'PreinvasiveComponent', 
                       explanatory = explanatory,
                       # column = TRUE,
                       total_col = TRUE,
                       p = TRUE,
                       add_dependent_label = TRUE,
                       na_include=FALSE
                       # catTest = catTestfisher
                       ) -> table

knitr::kable(table, row.names = FALSE, align = c('l', 'l', 'r', 'r', 'r'))
```

\pagebreak
```{r crosstable arsenal PreinvasiveComponent, message=FALSE, warning=FALSE, eval=FALSE, include=FALSE}

table1 <- arsenal::tableby(PreinvasiveComponent ~ explanatory, mydata)

summary(table1)

knitr::kable(table1,
                         row.names = FALSE,
                         align = c('l', 'l', 'r', 'r', 'r', 'r'),
                         format = 'html') %>%
                kableExtra::kable_styling(kable_input = .,
                                          bootstrap_options = 'striped',
                                          full_width = F,
                                          position = 'left')
```

\pagebreak
```{r crosstable tangram PreinvasiveComponent, message=FALSE, warning=FALSE, eval=FALSE, include=FALSE}
tangram::tangram(PreinvasiveComponent ~ explanatory, mydata)

```

\pagebreak
```{r crosstable tangram NEJM PreinvasiveComponent, message=FALSE, warning=FALSE, eval=FALSE, include=FALSE}
tangram::html5(tangram::tangram(PreinvasiveComponent ~ explanatory, mydata),
                    fragment = TRUE,
                    inline = 'nejm.css',
                    caption = 'Cross TablePreinvasiveComponentNEJM Style',
                    id = 'tbl3')
```

\pagebreak
```{r crosstable tangram Lancet PreinvasiveComponent, message=FALSE, warning=FALSE, eval=FALSE, include=FALSE}
tangram::html5(tangram::tangram(PreinvasiveComponent ~ explanatory, mydata),
                    fragment = TRUE,
                    inline = 'lancet.css',
                    caption = 'Cross TablePreinvasiveComponentLancet Style',
                    id = 'tbl3')
```

\pagebreak

